### ISSUE TITLE
13 chromosomes, only 12 chromosome displayed in plot.

### ISSUE THREAD

**Issue by wym0072003** [Atvar2/plotHicGenome#2]
Hi, 

Thanks for your nice tool.
I can see all 13 chromosomes in juicebox. After running PlotHicGenome with the following command line; only 12 chromosomes were displayed in the plot.

My command: _plotHicGenome juicer ./aligned/merged_nodups.txt ./review.assembly -W whole -n 13 -s True -l t -F 4 -r 500000 -X 2 -w 0.5 -d 3 -S 'dashed' -i 300 -z 6,6 -C 'black' -L 0.8 -A 0.8 -B '1%' -D 0.2 -o test-sorted-review.pdf -R ./run/_

![image](https://github.com/user-attachments/assets/78bf4afd-2e72-4cb3-8d1e-703a10440d95)

It looks like chr12 and chr13 overlapped at the x-axis's tail. Would you please let me know the reason and how to correct it?

Thanks.

Best,

Yiming

**Comment by Atvar2** [comment]
Hi, Yiming

I suppose the short length of chromosome 13 or the absence of Hi-C signals in the sparse matrix for chromosome 13 may be the reason. The software does not impose any restrictions on the number of chromosomes.

bets regards

**Comment by wym0072003** [comment]
> bets regards

Hi Junhui,

Thanks very much for your reply. 
I used the wrong assembly file to make the plot. I should use the ‘Final. assembly’ but mistakenly used the 'review.assembly'. I have got the right picture and thanks again for developing this nice tool.

Best,

Yiming
